metric: COCO
num_classes: 4

TrainDataset:
  name: COCODataSet
  image_dir: train
  anno_path: instance_train.json
  dataset_dir: dataset/custom_data_r
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: train
  anno_path: instance_train.json
  dataset_dir: dataset/custom_data_r
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: instance_train.json # also support txt (like VOC's label_list.txt)
  dataset_dir: dataset/custom_data_r # if set, anno_path will be 'dataset_dir/anno_path'
